### ISSUE TITLE
"Phantom worlds"

### ISSUE THREAD

**Issue by LogicParrot** [cuberite/cuberite#2810]
- Currently, when going to the nether/end for the first time, it is generated at runtime. This is heavy, and can freeze the tick thread and trigger the deadlock detector on weak devices like Rpis.
 - The newly generated worlds are "phantom worlds" - never mentioned in `settings.ini`.
 - Nether and End should be in `settings.ini` by default so that they aren't "phantom worlds" and are generated at first startup to avoid the deadlock detector issue.
 - Worlds that are referenced in `world.ini` but aren't in `settings.ini` (The so-called phantom worlds) should cause an error when server reads the config, and not generate a new world.
 - The above point means deprecating `cRoot::Get()->CreateAndInitializeWorld(...)`  (or at least using it only at server startup when a world is missing) and redoing #2462.

**Todo:**
 - [x] 1. Nether and End in `settings.ini` by default, and created at startup. #2815
 - [x] 2. Fix server configs created prior to the #2815 update. Done in #2821
 - [x] 3. Prevent generating phantom worlds in default configs. Done in #2953
 - [x] 4. Reject the existence of phantom worlds by config check at startup. Done in #2961
 - [x] 5. Remove `CreateAndInitializeWorld`. Done in #2962, unmerged.

**Original post:**
When traveling to the Nether for the first time, the folder `world_nether` is created. But the newly created world is never added in `settings.ini`. Is this a bug or intended?

**Comment by NiLSPACE** [comment]
The world should never be created in the first place. It's unsafe to add a world while the server is running.

**Comment by SafwatHalaby** [comment]
Would it be hard to generate the Nether an End on startup just like the overworld? Then we can have them in `settings.ini` by default.

**Comment by NiLSPACE** [comment]
I don't think Cuberite should generate a world if it's not defined by the admin himself in the `settings.ini`

If the admin defined a world in a `world.ini` while that world doesn't exist we should simply show an error message if you'd ask me.

**Comment by SafwatHalaby** [comment]
My test suggests that adding `World=world_nether` to `settings.ini` prior to first server startup is enough to resolve this. It generates both worlds properly. That should be in the ini file by default.

**Comment by SafwatHalaby** [comment]
This also prevents a world being generated at runtime, which you mentioned is unsafe @ #2462

**Comment by SafwatHalaby** [comment]
>I don't think Cuberite should generate a world if it's not defined by the admin himself in the settings.ini
>If the admin defined a world in a world.ini while that world doesn't exist we should simply show an error message if you'd ask me.

I completely agree. But the default ini should have a nether and an end in addition to the overworld.

**Comment by NiLSPACE** [comment]
Yeah, I agree with that. The default settings should provide as much of a vanilla experience as possible, and that includes the nether and end worlds.

**Comment by SafwatHalaby** [comment]
To sum it up:
 - Currently, when going to the nether/end for the first time, it is generated at runtime (my deadlock)
 - The newly generated worlds are "phantom worlds" - never mentioned in `settings.ini`.
 - Nether and end should be in `settings.ini` by default so that they aren't "phantom worlds" and are generated at first startup to avoid the deadlocking issue.
 - Worlds that are referenced in `world.ini` but aren't in `settings.ini` (The so-called phantom worlds) should cause an error, and not generate a new world.
 - The above point means ditching `cRoot::Get()->CreateAndInitializeWorld(...)` and redoing #2462

**Comment by NiLSPACE** [comment]
I don't think they were actually causing deadlocks, but when preparing the spawn they locked the tick thread. If it took more than an X amount of time the deadlock detector would think it's deadlocked.

**Comment by SafwatHalaby** [comment]
Okay, but the point that holds is that worlds should not be generated by players' actions.

**Comment by SafwatHalaby** [comment]
I have edited the initial post.

**Comment by worktycho** [comment]
I personally think that CreateAndInitializeWorld can be made safe. It's main problem at the moment is it does a large amount of work on the thread its called from. If we instead loaded the spawn chunks using the chunk loading processes, we could make CreateAndInitializeWorld asynchronous and execute in a couple of milliseconds.

**Comment by madmaxoft** [comment]
I still don't think it's a wise thing to do. The admin has set their worlds in settings.ini, who are we to change their setting behind their back?

The only sound reason for changing the world configuration is when the server is started up for the first time. At that moment, and that moment only, it's reasonable to assume the user wants some default configuration matching the default vanilla server.

So I propose, let's get rid of the `CreateAndInitializeWorld` function, at least from the API standpoint, and instead do a startup check - when reading settings.ini for the first time, if there are no worlds configured, create a proper default 3-world configuration (overworld, nether, end) before even initializing those worlds.
If, upon world initialization, the server finds an invalid link to a world through the world.ini file, I think it's a fair reason to emit an error message and abort the server completely - that is a kind of misconfiguration that the admin *needs* to look at and decide what to do.

**Comment by worktycho** [comment]
We should get rid of creating worlds within the server, but a safe way of creating worlds could be very useful for plugins.

**Comment by tigerw** [comment]
1. Let every world automatically generate a nether and end, in addition to the overworld, all of which are stored as dimensions in an enclosing world folder.
2. Let plugin world creation require a server restart, as per normal procedure.

**Comment by SafwatHalaby** [comment]
I wouldn't want any world I create to generate a nether and an end. Why should I generate 3 worlds for a jail or a Skyblock game?

**Comment by SafwatHalaby** [comment]
>There's also a different issue which I've been wondering about:
After linkage rules are enforced, how exactly would I create a new Nether? If I add a new world in settings.ini, a regular world would be created upon startup.

How about this? (explained in two examples)

** Example 1, The default `settings.ini` **

```
[Worlds]
DefaultWorld=world
WorldNether=world_nether
WorldEnd=world_end
```

** Example 2, Custom `settings.ini` **

```
[Worlds]
DefaultWorld=world
World=mySecondOverWorld
World=3rdOverWorld
WorldEnd=world_end
WorldNether=hellishWorld
WorldNether=jailForTheSinful
```

This allows the server to always create the right world type if a folder is missing. Resolving the issue mentioned in the quote. Also, the server would never autofill a `world.ini`'s LinkedWorlds unless both `settings.ini` and `world/` are both missing. In which case, the linked worlds are `world_end` and `world_nether`.

**Comment by tigerw** [comment]
> I wouldn't want any world I create to generate a nether and an end. Why should I generate 3 worlds for a jail or a Skyblock game?

Because it is the way both Vanilla and Bukkit handle this, and judging by the above post, also the easiest for anyone to understand.

**Comment by SafwatHalaby** [comment]
The above config is very simple.

**Comment by SafwatHalaby** [comment]
I removed my previous proposal because it has many flaws and is just adding noise.

I don't think we should automatically mimick Vanilla and Bukkit if we can do it better.
I actually like the current way it's handled, the only two problems are:

- Linkage to non-existent worlds is allowed.
- When adding a new world to settings.ini, the server would always generate an overworld-type world. 

Problem 1 can be solved easily.
As to problem 2, maybe the best way to handle that would be asking the player at the console. `A new world was added to settings.ini, please choose the template you want to use for that world: `nether, overworld, flat, amplified, etc. You can later tweak your new world or change its template by editing world.ini`.

**Comment by 36451** [comment]
Imo, having a way for plugins to create a world during server runtime would be a good thing, if it's not too hard to code.

**Comment by madmaxoft** [comment]
A plugin could always modify settings.ini (and create world.ini if desired) and then restart the server, or ask the admin to restart the server.

**Comment by NiLSPACE** [comment]
For plugin's, how about we create a method that allows them to create a new world (without blocking the server), and also delete world's if they are not defined in the settings.ini. Some plugins might have trouble with it though, since they expect world's to be non-stopable.

**Comment by madmaxoft** [comment]
It's still the same problem, once a world exists, it calls several hooks and ever since then plugins expect that the `cWorld` object they got in those hooks are valid.

I still think a plugin shouldn't be capable of creating or deleting new world directly, only via config change and server restart.

**Comment by Seadragon91** [comment]
I wanted to get a fresh nether world and deleted the folder world_nether. Started the server and joined to the nether world and see only overworld.

**Comment by LogicParrot** [comment]
Yes, this is a problem. My suggestion would solve it, but I'm not sure it's the best way.

```
A new world is at settings.ini, please choose the template you want to use for that world: (nether, overworld, flat, amplified, etc. are presented as choices) You can later tweak your new world or change its template by editing world.ini.
```

**Comment by LogicParrot** [comment]
#2953 prevents the server from linking to nonexisting worlds in default configs under any circumstances. When creating a new ini file, the server will attempt to do best-guessing and link the world to the proper worlds, but it will never link to a nonexisting world. e.g. The default ini for x_nether links it to x only if x exists.

**Comment by LogicParrot** [comment]
>I wanted to get a fresh nether world and deleted the folder world_nether. Started the server and joined to the nether world and see only overworld.

Fixed in #2953

**Comment by LogicParrot** [comment]
So... What's the decision regarding `CreateAndInitializeWorld()`? Should I remove it?

I personally agree with @madmaxoft, worlds should never be created at runtime. It's unexpected and logically weird. Plugins are free to edit config and restart.

**Comment by NiLSPACE** [comment]
I guess it's better to remove it.

**Comment by LogicParrot** [comment]
Anyone planning on reviewing the PRs?
