### ISSUE TITLE
Forum Migration ToDo

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite#2937]
Here is what still needs to be done in order to complete the forum trasnfer. 
I wasn't involved in the transfer so I probably missed many things. Feel free to edit this and add your own.
- [x] Make mc-server.org redirect (301 moved permanently preferred) to forum.cuberite.org. An old thread url should lead to that same thread at the new domain, and not to the homepage.
- [x] Solve the 2-urls-per-post issue which is described in the comments.
- [x] Substitute all occurences of  `[url=http://mc-server.org]` in all forum posts with `[url=http://forum.cuberite.org]`

**Comment by LogicParrot** [comment]
It appears I lost my moderation power in the servers subsection.

**Comment by SphinxC0re** [comment]
I already replaced all occurences of `http://forum.mc-server.org` with `https://forum.cuberite.org`

**Comment by LogicParrot** [comment]
Marked as done.

Mods/admins/everyone: Consider changing the password now that we're using https, just in case.

**Comment by LogicParrot** [comment]
I think we have a serious SEO issue now. Every post has 2 urls, this is bad.

https://forum.cuberite.org/thread-1983.html
https://forum.cuberite.org/showthread.php?tid=1983

**Comment by LogicParrot** [comment]
http://mc-server.org/showthread.php?tid=1983 redirects to a 404 not found, this is bad. It should redirect to https://forum.cuberite.org/showthread.php?tid=1983

**Comment by NiLSPACE** [comment]
You mean http://forum.mc-serv.... ?

**Comment by LogicParrot** [comment]
I fixed my comment. There is still a problem though.

**Comment by LogicParrot** [comment]
Does anyone have raw php access? Fixing the mc-server redirect should be easy.

**Comment by NiLSPACE** [comment]
Only @FakeTruth has access to that.

**Comment by LogicParrot** [comment]
@NiLSPACE It's generally a bad practice. Especially SEO-wise. ( it may confuse search engine indexing and thus make the website rank less), but it's also confusing needlessly.

**Comment by BitOfAByte** [comment]
On the [milestones](https://github.com/cuberite/cuberite/milestones) page the "Good Survival" and the "AI" section both have links to the old forum.

**Comment by NiLSPACE** [comment]
so.. what link should we keep? The showthread.php or the thread-<num>?

If we use the last one all links in and outside the forum will not work, while if we use the showthread.php we use unclean links which Google prefers not to have.

**Comment by mathias-github** [comment]
We could probably redirect showthread.php to thread-[num].html with .htaccess

**Comment by LogicParrot** [comment]
Someone should Faketruth to set up mc-server > cuberite redirects, or simply to give us server access.

**Comment by LogicParrot** [comment]
Marking this as `important` because SEO is serious, and broken mc-server.org links are serious.

**Comment by rekuen** [comment]
As mathias stated you could solve the 2 url situation with a simple url redirect in .htaccess , and for the time being you could one of the urls as canonical to the other one, is the same as a 301 redirect for google and is used to mark duplicated content.

**Comment by LogicParrot** [comment]
Yes, but I have no server access at all.

**Comment by rekuen** [comment]
Not even FTP?

**Comment by mathias-github** [comment]
The 2-urls-per-post issue is fixed.

**Comment by SphinxC0re** [comment]
Woot? Cool

**Comment by LogicParrot** [comment]
Great :)

Should I contact Faketruth, or did anyone try to do so already?

**Comment by SphinxC0re** [comment]
Yes, I did. He didn't respond yet

**Comment by LogicParrot** [comment]
I think it's time for another substitution:
Substitute all `[url=http://forum.cuberite.org` with `[url=https://forum.cuberite.org`

**Comment by Schwertspize** [comment]
(https:)

Is that really necessary or can't we just use the "normal" htaccess rewrite?

**Comment by LogicParrot** [comment]
A normal redirect is prone to downgrade attacks. For maximum security, we should substitute and/or use the [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) header.

**Comment by mathias-github** [comment]
I think HSTS is already used on the forum.

**Comment by SphinxC0re** [comment]
I will do it this weekend

**Comment by LogicParrot** [comment]
The major issues are all fixed now :)
mc-server properly redirects to cuberite.

**Comment by mathias-github** [comment]
Bump @SphinxC0re

**Comment by SphinxC0re** [comment]
Why me?

**Comment by mathias-github** [comment]
Did you enable HSTS on the forum?

**Comment by LogicParrot** [comment]
The `Strict-Transport-Security` http header is not being sent, so, no.

**Comment by LogicParrot** [comment]
I'd say we substitute anyways. This covers older browsers.

>Substitute all [url=http://forum.cuberite.org with [url=https://forum.cuberite.org

**Comment by madmaxoft** [comment]
I'd say the forum migration is finished, shall we close this?

**Comment by Cl1608Ho** [comment]
Yes!

**Comment by madmaxoft** [comment]
What exactly is the problem with that? The forum allows you to link to a specific post in any thread, so there have to be multiple URLs.

**Comment by williamhatcher** [comment]
Considering the age of this and that most, if not all issue have been addressed, I think it's time to close this

**Comment by LogicParrot** [comment]
It's generally unclean to have multiple links point to the same content. (For instance, the browser's cache treats the two duplicates as totally separate things).

The previous scheme was better. The post was just the hash part. Something like `thread-2504-page-3#postAnchor`

**Comment by LogicParrot** [comment]
This is not addressed yet.

**Comment by mathiascode** [comment]
This is default behavior, not worth the effort.
