### ISSUE TITLE
Missing features in old versions

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#4888]
### Version 1.0
The End:
- [ ] Overworld fortress
- [ ] Generation of the End
- [ ] Being able to throw Eye of Ender
- [ ] Leaving the end
- [ ] Monster spawn stone bricks

Mobs:
- [ ] Ender Dragon
- [ ] Spawning Villager in Villages (No trading until 1.3)

### Version 1.1
- [ ] Blacksmith buildings in villages now have a chest that contains loot.
- [ ] Non-operator users are auto-kicked in multiplayer servers if they spam in chat too much.
       Operators are not notified of the kick; they must assume that the user was auto-kicked.

### Version 1.2.1
- [ ] Iron Golem spawning in Villages
- [ ] Zombie Sieges
- [ ] Villager Breeding
- [ ] Wolf Breeding

### Version 1.3.1
- [ ] Wood Blocks (the ones with the texture on all sides)
- [ ] Villager trading
- [ ] Writing books
- [ ] Starting Chest
- [ ] Large Biomes Generator (?)

### Version 1.4.2
- [ ] Pumpkin Pie
- [ ] Wither Boss bar
- [ ] Whitch
- [ ] Mob Spawner specialized NBT tags to spawn equiped mobs
- [ ] NBT tags as potion descriptors
- [ ] Carrots and potatoes can be found in farms in villages

### Version 1.5
- [ ] Daylight sensor
- [ ] New Rails
- [ ] New Minecarts
- [ ] Abandoned mineshaft: Now spawn items in minecarts with chests, instead of chests
- [ ] Renamed item containers will now display that name when viewing the container's contents
- [ ] Renamed Command Blocks now use their name instead of @ in the chat

### Version 1.6
- [ ] Horse Riding
- [ ] Attribute system
- [ ] Added chest generation in nether fortresses

### Version 1.7
- [ ] colored glass / glass panels
- [ ] proper packed ice
- [ ] Block with mobs in them (e.g. silver fish)
- [ ] Minecart with command block
- [ ] Witch huts now generate with a witch inside.

This list does not claim be to be complete. I went through the patch notes on the wiki and tried out some stuff. It's just a start.

I'll try to link the matching issues

**Comment by AndreaSmetankova** [comment]
Hi, I would like to help but I'm new to this and find this repositar only recently. Can you advise me where to start?

**Comment by 12xx12** [comment]
Hi,

we have a discord and a forum if there any questions. there are some issues marked with the label effort/easy. that's a good way to get to know the codebase.

Check the website for the links!

**Comment by PureTryOut** [comment]
I just want to say thanks for keeping track of this. My main reason for not using Cuberite actively is because I purely play survival and it misses the required features to do so to to the fullest. I've been annoyed by this in the past and is the main reason I left the project as a user and plugin developer a few years ago.

I still have the opinion that working to implement all missing vanilla features up to a certain MC version (e.g. 1.12.0) is better than trying to add random things from newer versions, hopefully this tracking issue will help with that.

**Comment by Titaniumtown** [comment]
@PureTryOut same, I use Yatopia while I'm waiting for Cuberite to be good for survival servers. Yatopia is the fastest (afaik) java edition server out there.

**Comment by tigerw** [comment]
Our users have spoken!

**Comment by 12xx12** [comment]
No more new feature PRs till this is closes 😇😂😉😉😉😉 *wink*

**Comment by PureTryOut** [comment]
A list of missing mobs and entities of 1.8 and up is available in https://github.com/cuberite/cuberite/issues/3499.

I'll test more versions up to 1.12 and will update this post with stuff I find.

# Version 1.8

- [ ] Arrows should slow down under water #5036
- [ ] Villagers don't harvest crops #5037
- [ ] Pets should show death message if named with a name tag #5038

# Version 1.12

- [ ] Advancements #3770

**Comment by PureTryOut** [comment]
@12xx12 #5047 has been resolved.

**Comment by PureTryOut** [comment]
@1285done #5039 has been resolved.
#5041 also has been resolved a while ago.

**Comment by DarkoGNU** [comment]
> **Version 1.8**
> - [ ] Pets should show death message if named with a name tag #5038

This is now fixed

**Comment by 12xx12** [comment]
I like the new way git displays the references - you can now see if a issue is closed

**Comment by PureTryOut** [comment]
*Github, nothing "Git" about it :wink: 

But yeah, that does look nice!

**Comment by creeperpaint** [comment]
Mules need to be implemented #5474
